DEBUG = False
API_URL_PREFIX = '/api'

# MAIL
MAIL_SERVER='localhost'
MAIL_PORT=25
MAIL_USE_TLS=False
MAIL_USE_SSL=False
MAIL_DEBUG=False
MAIL_USERNAME=None
MAIL_PASSWORD=None
MAIL_DEFAULT_SENDER=None
MAIL_MAX_EMAILS=None
MAIL_SUPPRESS_SEND=False
MAIL_ASCII_ATTACHMENTS=False
